apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus
spec:
  groups:
  - name: prometheus.rules
    rules:
    - alert: PrometheusCantScrape
      # Alert only if there are jobs but no samples scraped.
      expr: scrape_samples_scraped == 0 and on(job) up{job!~".*shoot-etcd-druid"} == 1
      for: 1h
      labels:
        service: prometheus
        severity: warning
        type: seed
        visibility: operator
      annotations:
        description: Prometheus failed to scrape metrics. Instance {{ $labels.instance }}, job {{ $labels.job }}.
        summary: No metrics are scraped from any target.
    - alert: PrometheusConfigurationFailure
      expr: prometheus_config_last_reload_successful == 0
      for: 1h
      labels:
        service: prometheus
        severity: warning
        type: seed
        visibility: operator
      annotations:
        description: Latest Prometheus configuration is broken and Prometheus is using the previous one.
        summary: Prometheus is misconfigured
    - alert: SomethingIsFailing
      expr: vector(1)
      for: 10m
      labels:
        type: healthcheck
      annotations:
        summary: Something is failing in the shoot.
        description: This alert is used to indicate that something is failing in the seed.
