package plutono

import "github.com/gardener/gardener/pkg/component"

func Dashboards(values Values) []string {
	if values.ClusterType == component.ClusterTypeSeed && !values.IsGardenCluster && !values.VPAEnabled {
		return []string{
			"alerts-dashboard.json",
			"client-go.json",
			"controller-details.json",
			"controllers.json",
			"extensions-dashboard.json",
			"fluent-bit-dashboard.json",
			"gardener-resource-usage-by-container.json",
			"gardener-resource-usage.json",
			"istio-control-plane-dashboard.json",
			"istio-ingress-gateway-dashboard.json",
			"istio-mesh-dashboard.json",
			"pod-logs.json",
			"seed-deployments-replicas.json",
			"seed-resource-usage.json",
			"shoot-control-plane-resource-usage-by-owner-container.json",
			"shoot-control-plane-resource-usage-overview.json",
			"shoot-control-plane-resource-usage.json",
			"shoot-operation-duration.json",
			"systemd-logs.json",
			"webhook-details.json",
			"webhooks.json",
		}
	}

	if values.ClusterType == component.ClusterTypeSeed && !values.IsGardenCluster && values.VPAEnabled {
		return []string{
			"alerts-dashboard.json",
			"client-go.json",
			"controller-details.json",
			"controllers.json",
			"extensions-dashboard.json",
			"fluent-bit-dashboard.json",
			"gardener-resource-usage-by-container.json",
			"gardener-resource-usage.json",
			"istio-control-plane-dashboard.json",
			"istio-ingress-gateway-dashboard.json",
			"istio-mesh-dashboard.json",
			"pod-logs.json",
			"seed-deployments-replicas.json",
			"seed-resource-usage.json",
			"shoot-control-plane-resource-usage-by-owner-container.json",
			"shoot-control-plane-resource-usage-overview.json",
			"shoot-control-plane-resource-usage.json",
			"shoot-operation-duration.json",
			"systemd-logs.json",
			"vpa-admission-controller.json",
			"vpa-dashboard.json",
			"vpa-recommender.json",
			"webhook-details.json",
			"webhooks.json",
		}
	}

	if values.ClusterType == component.ClusterTypeSeed && values.IsGardenCluster && !values.VPAEnabled {
		return []string{
			"alerts-dashboard.json",
			"apiserver-admission-details.json",
			"apiserver-overview.json",
			"apiserver-request-details.json",
			"apiserver-request-duration-and-response-size.json",
			"apiserver-storage-details.json",
			"apiserver-watch-details.json",
			"container-runtime.json",
			"garden-alertmanager-dashboard.json",
			"garden-availability-dashboard.json",
			"garden-resource.json",
			"gardener-admission-controller-dashboard.json",
			"gardener-admission-controller-seedauthorizer-details.json",
			"gardener-controlplane.json",
			"kubernetes-pods-dashboard.json",
			"resource-usage-by-container.json",
			"seed-resource-usage-dashboard.json",
			"shoot-availability-dashboard.json",
			"shoot-details-dashboard.json",
			"shoot-sla-dashboard.json",
			"shoot-sli-dashboard.json",
			"virtual-garden-etcd-backup-dashboard.json",
			"virtual-garden-etcd-dashboard.json",
		}
	}

	if values.ClusterType == component.ClusterTypeSeed && values.IsGardenCluster && values.VPAEnabled {
		return []string{
			"alerts-dashboard.json",
			"apiserver-admission-details.json",
			"apiserver-overview.json",
			"apiserver-request-details.json",
			"apiserver-request-duration-and-response-size.json",
			"apiserver-storage-details.json",
			"apiserver-watch-details.json",
			"container-runtime.json",
			"garden-alertmanager-dashboard.json",
			"garden-availability-dashboard.json",
			"garden-resource.json",
			"gardener-admission-controller-dashboard.json",
			"gardener-admission-controller-seedauthorizer-details.json",
			"gardener-controlplane.json",
			"kubernetes-pods-dashboard.json",
			"resource-usage-by-container.json",
			"seed-resource-usage-dashboard.json",
			"shoot-availability-dashboard.json",
			"shoot-details-dashboard.json",
			"shoot-sla-dashboard.json",
			"shoot-sli-dashboard.json",
			"virtual-garden-etcd-backup-dashboard.json",
			"virtual-garden-etcd-dashboard.json",
			"vpa-admission-controller.json",
			"vpa-dashboard.json",
			"vpa-recommender.json",
		}
	}

	if values.ClusterType == component.ClusterTypeShoot && !values.IsWorkerless && !values.IncludeIstioDashboards && !values.VPAEnabled && !values.VPNHighAvailabilityEnabled {
		return []string{
			"apiserver-admission-details.json",
			"apiserver-overview.json",
			"apiserver-request-details.json",
			"apiserver-request-duration-and-response-size.json",
			"apiserver-storage-details.json",
			"apiserver-watch-details.json",
			"client-go.json",
			"cluster-overview-dashboard.json",
			"container-images.json",
			"controller-details.json",
			"controllers.json",
			"controlplane-logs-dashboard.json",
			"dns-dashboard.json",
			"envoy-proxy-dashboard.json",
			"etcd-backup-dashboard.json",
			"etcd-cluster-details-dashboard.json",
			"etcd-compaction-job-dashboard.json",
			"etcd-dashboard.json",
			"kubernetes-api-server-details.json",
			"kubernetes-api-server-watches-dashboard.json",
			"kubernetes-control-plane-status-dashboard.json",
			"kubernetes-daemonsets-dashboard.json",
			"kubernetes-deployments-dashboard.json",
			"kubernetes-pods-dashboard.json",
			"kubernetes-statefulsets-dashboard.json",
			"mcm-dashboard.json",
			"node-details-dashboard.json",
			"node-pool-dashboard.json",
			"prometheus-dashboard.json",
			"shoot-control-plane-resource-usage-by-owner-container.json",
			"vpn-dashboard.json",
			"webhook-details.json",
			"webhooks.json",
		}
	}

	if values.ClusterType == component.ClusterTypeShoot && !values.IsWorkerless && values.IncludeIstioDashboards && values.VPAEnabled && values.VPNHighAvailabilityEnabled {
		return []string{
			"apiserver-admission-details.json",
			"apiserver-overview.json",
			"apiserver-proxy-dashboard.json",
			"apiserver-request-details.json",
			"apiserver-request-duration-and-response-size.json",
			"apiserver-storage-details.json",
			"apiserver-watch-details.json",
			"client-go.json",
			"cluster-overview-dashboard.json",
			"container-images.json",
			"controller-details.json",
			"controllers.json",
			"controlplane-logs-dashboard.json",
			"dns-dashboard.json",
			"etcd-backup-dashboard.json",
			"etcd-cluster-details-dashboard.json",
			"etcd-compaction-job-dashboard.json",
			"etcd-dashboard.json",
			"kubernetes-api-server-details.json",
			"kubernetes-api-server-watches-dashboard.json",
			"kubernetes-control-plane-status-dashboard.json",
			"kubernetes-daemonsets-dashboard.json",
			"kubernetes-deployments-dashboard.json",
			"kubernetes-pods-dashboard.json",
			"kubernetes-statefulsets-dashboard.json",
			"mcm-dashboard.json",
			"node-details-dashboard.json",
			"node-pool-dashboard.json",
			"prometheus-dashboard.json",
			"shoot-control-plane-resource-usage-by-owner-container.json",
			"vpa-admission-controller.json",
			"vpa-dashboard.json",
			"vpa-recommender.json",
			"vpn-dashboard.json",
			"vpn-seed-server-dashboard.json",
			"webhook-details.json",
			"webhooks.json",
		}
	}

	return nil
}
